-- ══════════════════════════════════════════════════════════════════════════════
-- Migration 005 — Bot-code authentication table
-- Run in: Supabase Dashboard → SQL Editor → New Query → Run
-- ══════════════════════════════════════════════════════════════════════════════

-- One-time auth codes generated by the website, claimed by the Telegram bot.
CREATE TABLE IF NOT EXISTS public.auth_codes (
  code        text        PRIMARY KEY,                  -- random 8-char hex
  telegram_id bigint,                                   -- set when bot claims the code
  first_name  text,
  username    text,
  photo_url   text,
  created_at  timestamptz NOT NULL DEFAULT now(),
  expires_at  timestamptz NOT NULL DEFAULT now() + interval '10 minutes',
  used        boolean     NOT NULL DEFAULT false
);

-- Auto-clean expired codes (optional, run periodically or via pg_cron)
-- DELETE FROM public.auth_codes WHERE expires_at < now();

-- Index for fast lookup by code
CREATE INDEX IF NOT EXISTS idx_auth_codes_expires ON public.auth_codes (expires_at);

-- RLS: backend service role bypasses RLS; anon reads nothing
ALTER TABLE public.auth_codes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "auth_codes: no anon access" ON public.auth_codes;
CREATE POLICY "auth_codes: no anon access"
  ON public.auth_codes
  FOR ALL
  TO anon
  USING (false);
